### PR TITLE
d912pxy support patch

### PR DESCRIPTION
**Pull request by megai2**
https://github.com/Friendly0Fire/GW2Radial/issues/100 related

-replace d3dx with 
   * custom Effect class 
   * custom dds texture loader
   * vs & ps *.hlsl pair instead of *.fx one
   * other custom types
-replace draw primitive with draw indexed primitive
-add load of d912pxy.dll when found, instead of system d3d9.dll
-add custom dx9 imgui implemenation with d912pxy support
-add custom Effect implemenation with d912pxy support

NOTE: i found exit crash with d912pxy, but not found source of it, but in general all things work. 
suggested source - chainloading and hooking

### CODE REVIEW

**Comment by Friendly0Fire** [comment]
So I took a look at this and I very much appreciate the amount of effort you've put into this. I just wanted to know: is there a way the DX12-specific variants and "magic" state variables could be eliminated? I don't like having such a direct dependency in the code since it could so easily break later on if we don't patch in sync.

**Comment by megai2** [comment]
> 
> 
> So I took a look at this and I very much appreciate the amount of effort you've put into this. I just wanted to know: is there a way the DX12-specific variants and "magic" state variables could be eliminated? I don't like having such a direct dependency in the code since it could so easily break later on if we don't patch in sync.

Only if you made state tracking by yourself. 

While state can be saved on d912pxy side, this approach will add unwanted memory writes on very "hot" API calls (~4Mcalls/sec) giving noticeable performance drop.

That is why  Get*** functions are not working and StateBlock too.
So you should track any state changing call and waste memory bandwidth and CPU time.

**Comment by megai2** [comment]
So i fixed exit crash and make dx12 specific code less intrusive to base code.

Now almost all dx12 related things are in Effect_dx12 and imgui patch. 
Things that are in base code:
1. d912pxy detection for Effect class 
2. d912pxy load instead of system d3d9 due to hooking logic used (maybe you can improve it, won't touch this in another way cuz it's tricky)

Considering incompat. errors that can rise later, i can change magic state on my end, so it will use default code until patched back. Or you can change it if something will not work from your changes.

**Comment by Friendly0Fire** [comment]
Greatly appreciate the work you've done with this, cheers! I'll take a look when I have some time, been rather busy lately unfortunately.

**Pull request merged**
